/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/crain-cn/cluster-mesh/api/cloud.mesh/v1beta1"
	scheme "github.com/crain-cn/cluster-mesh/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterMeshesGetter has a method to return a ClusterMeshInterface.
// A group's client should implement this interface.
type ClusterMeshesGetter interface {
	ClusterMeshes(namespace string) ClusterMeshInterface
}

// ClusterMeshInterface has methods to work with ClusterMesh resources.
type ClusterMeshInterface interface {
	Create(*v1beta1.ClusterMesh) (*v1beta1.ClusterMesh, error)
	Update(*v1beta1.ClusterMesh) (*v1beta1.ClusterMesh, error)
	UpdateStatus(*v1beta1.ClusterMesh) (*v1beta1.ClusterMesh, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.ClusterMesh, error)
	List(opts v1.ListOptions) (*v1beta1.ClusterMeshList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ClusterMesh, err error)
	ClusterMeshExpansion
}

// clusterMeshes implements ClusterMeshInterface
type clusterMeshes struct {
	client rest.Interface
	ns     string
}

// newClusterMeshes returns a ClusterMeshes
func newClusterMeshes(c *CloudV1beta1Client, namespace string) *clusterMeshes {
	return &clusterMeshes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterMesh, and returns the corresponding clusterMesh object, and an error if there is any.
func (c *clusterMeshes) Get(name string, options v1.GetOptions) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterMeshes that match those selectors.
func (c *clusterMeshes) List(opts v1.ListOptions) (result *v1beta1.ClusterMeshList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ClusterMeshList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustermeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterMeshes.
func (c *clusterMeshes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clustermeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterMesh and creates it.  Returns the server's representation of the clusterMesh, and an error, if there is any.
func (c *clusterMeshes) Create(clusterMesh *v1beta1.ClusterMesh) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clustermeshes").
		Body(clusterMesh).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterMesh and updates it. Returns the server's representation of the clusterMesh, and an error, if there is any.
func (c *clusterMeshes) Update(clusterMesh *v1beta1.ClusterMesh) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(clusterMesh.Name).
		Body(clusterMesh).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterMeshes) UpdateStatus(clusterMesh *v1beta1.ClusterMesh) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(clusterMesh.Name).
		SubResource("status").
		Body(clusterMesh).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterMesh and deletes it. Returns an error if one occurs.
func (c *clusterMeshes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterMeshes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustermeshes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterMesh.
func (c *clusterMeshes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clustermeshes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
