/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	scheme "client/clientset/versioned/scheme"
	"context"
	"time"

	v1beta1 "github.com/crain-cn/cluster-mesh/api/cloud.mesh/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterMeshesGetter has a method to return a ClusterMeshInterface.
// A group's client should implement this interface.
type ClusterMeshesGetter interface {
	ClusterMeshes(namespace string) ClusterMeshInterface
}

// ClusterMeshInterface has methods to work with ClusterMesh resources.
type ClusterMeshInterface interface {
	Create(ctx context.Context, clusterMesh *v1beta1.ClusterMesh, opts v1.CreateOptions) (*v1beta1.ClusterMesh, error)
	Update(ctx context.Context, clusterMesh *v1beta1.ClusterMesh, opts v1.UpdateOptions) (*v1beta1.ClusterMesh, error)
	UpdateStatus(ctx context.Context, clusterMesh *v1beta1.ClusterMesh, opts v1.UpdateOptions) (*v1beta1.ClusterMesh, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ClusterMesh, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ClusterMeshList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterMesh, err error)
	ClusterMeshExpansion
}

// clusterMeshes implements ClusterMeshInterface
type clusterMeshes struct {
	client rest.Interface
	ns     string
}

// newClusterMeshes returns a ClusterMeshes
func newClusterMeshes(c *CloudV1beta1Client, namespace string) *clusterMeshes {
	return &clusterMeshes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterMesh, and returns the corresponding clusterMesh object, and an error if there is any.
func (c *clusterMeshes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterMeshes that match those selectors.
func (c *clusterMeshes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ClusterMeshList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ClusterMeshList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustermeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterMeshes.
func (c *clusterMeshes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clustermeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterMesh and creates it.  Returns the server's representation of the clusterMesh, and an error, if there is any.
func (c *clusterMeshes) Create(ctx context.Context, clusterMesh *v1beta1.ClusterMesh, opts v1.CreateOptions) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clustermeshes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterMesh).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterMesh and updates it. Returns the server's representation of the clusterMesh, and an error, if there is any.
func (c *clusterMeshes) Update(ctx context.Context, clusterMesh *v1beta1.ClusterMesh, opts v1.UpdateOptions) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(clusterMesh.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterMesh).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterMeshes) UpdateStatus(ctx context.Context, clusterMesh *v1beta1.ClusterMesh, opts v1.UpdateOptions) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(clusterMesh.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterMesh).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterMesh and deletes it. Returns an error if one occurs.
func (c *clusterMeshes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterMeshes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustermeshes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterMesh.
func (c *clusterMeshes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterMesh, err error) {
	result = &v1beta1.ClusterMesh{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clustermeshes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
