apiVersion: cloud.mesh/v1beta1
kind: Cluster
metadata:
  name: k8s-test
spec:
  name: "测试环境物理机集群"
  description: "测试环境物理机集群"
  apiServer: "https://127.0.0.1:16443"
  kubeConfig: |-
    {
      "apiVersion": "v1",
      "clusters": [
        {
          "cluster": {
            "certificate-authority-data": "",
            "server": "https://127.0.0.1:16443"
          },
          "name": "kubernetes"
        }
      ],
      "contexts": [
        {
          "context": {
            "cluster": "kubernetes",
            "user": "kubernetes-admin"
          },
          "name": "kubernetes-admin@kubernetes"
        }
      ],
      "current-context": "kubernetes-admin@kubernetes",
      "kind": "Config",
      "preferences": {
      },
      "users": [
        {
          "name": "kubernetes-admin",
          "user": {
            "client-certificate-data": "",
            "client-key-data": ""
          }
        }
      ]
    }
  environment: "test"
  supportEnv:
    test:
      defaultNodeGroup: app
      reportGateway: ingress-endpoint
      defaultResourceRequirements:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: 50m
          memory: 1Gi
      defaultIngressController: default
      minPermission: namespace-owner
      supportGateway: true
      gatewayConfig:
        gatewaySign: xt_ada731d53c578705957ed528b57aca3c
        baseURL: http://gwadmin.test.com
      gatewayClusters:
        - id: 2
          type: API
          description: 测试环境API
        - id: 3
          type: HA
          description: 测试环境HA
      dnsColicy: Default
      dnsConfig:
    dev:
      defaultNodeGroup: app
      defaultResourceRequirements:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: 50m
          memory: 1Gi
      defaultIngressController: default
      minPermission: namespace-owner
      supportGateway: false
      dnsColicy: Default
      dnsConfig:
  ciCluster: true
  clusterType: "std-idc"
  registryDomain: "hub.test.com"
  notice: ""
  initComplete: true
  supportSLB: false
  serviceSubnet: "10.12.0.0/16"